{"name": "Тест подтверждения отправки нового заказа с хэдера", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'В' is invalid: Введите корректную фамилию", "trace": "self = <test_order.TestOrder object at 0x7ff0183a2710>\nwebdriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"b6f36be2-f1ef-4f8a-9ff2-33fb34b46886\")>\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"b6f36be2-f1ef-4f8a-9ff2-33fb34b46886\")>\n\n    @allure.title('Тест подтверждения отправки нового заказа с хэдера')\n    @allure.description('Переходим к созданию нового заказа через кнопку в хэдере, \\\n                        заполняем необходимые поля и подтверждаем отправку заказа, \\\n                        проверяем, что заказ получил свой ID')\n    def test_order_from_header_confirm(self, webdriver: WebDriver, wait: WebDriverWait):\n        self.__enter_order_from_header(webdriver, wait)\n>       self.__fill_order_common(webdriver, wait)\n\ntests/test_order.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/test_order.py:101: in __fill_order_common\n    order_customer_page.check_valid_last_name()\npages/order_customer_page.py:63: in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.order_customer_page.OrderCustomerPage object at 0x7ff01826b690>\nlocator = ['xpath', './/input[starts-with(@class, \"Input_Input\") and contains(@placeholder, \"Фамилия\")]']\n\n    def __check_valid_input(self, locator: List[str]):\n        input_element = self.webdriver.find_element(*locator)\n    \n        given_value = input_element.get_attribute('value')\n    \n        input_element.clear()\n        input_element.send_keys(given_value)\n    \n        error_locator = [By.XPATH, f'{locator[1]}/../div']\n    \n        error_element = self.webdriver.find_element(*error_locator)\n    \n        is_valid = len(error_element.text) == 0\n    \n        if not is_valid:\n            allure.attach(\n                body=self.webdriver.get_screenshot_as_png(),\n                name='form-customer-input-validation-error',\n                attachment_type=allure.attachment_type.PNG)\n    \n>       assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\nE       AssertionError: Input 'В' is invalid: Введите корректную фамилию\n\npages/order_customer_page.py:98: AssertionError"}, "description": "Переходим к созданию нового заказа через кнопку в хэдере,                         заполняем необходимые поля и подтверждаем отправку заказа,                         проверяем, что заказ получил свой ID", "steps": [{"name": "Клик на кнопку согласия на использование cookies", "status": "passed", "start": 1681664714862, "stop": 1681664715303}, {"name": "Клик на кнопку Заказать", "status": "passed", "start": 1681664715303, "stop": 1681664715592}, {"name": "Ввод информации о заказчике: имя", "status": "passed", "parameters": [{"name": "value", "value": "'Мироновна'"}], "start": 1681664715593, "stop": 1681664715668}, {"name": "Проверка валидности ввода: имя", "status": "passed", "start": 1681664715668, "stop": 1681664715891}, {"name": "Ввод информации о заказчике: фамилия", "status": "passed", "parameters": [{"name": "value", "value": "'Валентина'"}], "start": 1681664715892, "stop": 1681664715935}, {"name": "Проверка валидности ввода: фамилия", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'В' is invalid: Введите корректную фамилию\n", "trace": "  File \"/home/user/qa_python_4/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 63, in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 98, in __check_valid_input\n    assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\n"}, "attachments": [{"name": "form-customer-input-validation-error", "source": "e73c705d-179d-416b-9374-a5834aefe6bc-attachment.png", "type": "image/png"}], "start": 1681664715935, "stop": 1681664716167}], "start": 1681664714862, "stop": 1681664716168, "uuid": "213a2aee-9a12-4631-b391-92ff0572ef4e", "historyId": "4dfaf0740abd6568790bae6ee91b09be", "testCaseId": "66b80ed8715398d53e8f3638942a4f14", "fullName": "tests.test_order.TestOrder#test_order_from_header_confirm", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrder"}, {"name": "host", "value": "workstation"}, {"name": "thread", "value": "181176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}