{"name": "Тест получения статуса заказа со страницы успешного завершения оформления заказа", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'С' is invalid: Введите корректную фамилию", "trace": "self = <test_track.TestTrack object at 0x7fbc047d0fd0>\nwebdriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"b8bf4d5a-a1d6-46a2-9e05-36b7fadf8479\")>\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"b8bf4d5a-a1d6-46a2-9e05-36b7fadf8479\")>\n\n    @allure.title('Тест получения статуса заказа со страницы успешного завершения оформления заказа')\n    @allure.description('Создаём заказ, кликаем на кнопку **Посмотреть статус** сразу после создания заказа, \\\n                        проверяем, что на странице присутствует блок информации о заказе')\n    def test_get_order_status_on_completed(self, webdriver: WebDriver, wait: WebDriverWait):\n        base_page = BasePage(webdriver, wait)\n    \n        base_page.click_button_accept_cookies()\n        base_page.click_button_order()\n    \n>       self.__make_order_common(webdriver, wait)\n\ntests/test_track.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/test_track.py:71: in __make_order_common\n    order_customer_page.check_valid_last_name()\npages/order_customer_page.py:63: in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.order_customer_page.OrderCustomerPage object at 0x7fbc04697650>\nlocator = ['xpath', './/input[starts-with(@class, \"Input_Input\") and contains(@placeholder, \"Фамилия\")]']\n\n    def __check_valid_input(self, locator: List[str]):\n        input_element = self.webdriver.find_element(*locator)\n    \n        given_value = input_element.get_attribute('value')\n    \n        input_element.clear()\n        input_element.send_keys(given_value)\n    \n        error_locator = [By.XPATH, f'{locator[1]}/../div']\n    \n        error_element = self.webdriver.find_element(*error_locator)\n    \n        is_valid = len(error_element.text) == 0\n    \n        if not is_valid:\n            allure.attach(\n                body=self.webdriver.get_screenshot_as_png(),\n                name='form-customer-input-validation-error',\n                attachment_type=allure.attachment_type.PNG)\n    \n>       assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\nE       AssertionError: Input 'С' is invalid: Введите корректную фамилию\n\npages/order_customer_page.py:98: AssertionError"}, "description": "Создаём заказ, кликаем на кнопку **Посмотреть статус** сразу после создания заказа,                         проверяем, что на странице присутствует блок информации о заказе", "steps": [{"name": "Клик на кнопку согласия на использование cookies", "status": "passed", "start": 1681664721483, "stop": 1681664721813}, {"name": "Клик на кнопку Заказать", "status": "passed", "start": 1681664721814, "stop": 1681664722092}, {"name": "Ввод информации о заказчике: имя", "status": "passed", "parameters": [{"name": "value", "value": "'Бенедиктович'"}], "start": 1681664722094, "stop": 1681664722170}, {"name": "Проверка валидности ввода: имя", "status": "passed", "start": 1681664722170, "stop": 1681664722284}, {"name": "Ввод информации о заказчике: фамилия", "status": "passed", "parameters": [{"name": "value", "value": "'Спартак'"}], "start": 1681664722284, "stop": 1681664722309}, {"name": "Проверка валидности ввода: фамилия", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'С' is invalid: Введите корректную фамилию\n", "trace": "  File \"/home/user/qa_python_4/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 63, in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 98, in __check_valid_input\n    assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\n"}, "attachments": [{"name": "form-customer-input-validation-error", "source": "0c08918e-5b25-40fe-8c1f-54caa97d0749-attachment.png", "type": "image/png"}], "start": 1681664722309, "stop": 1681664722400}], "start": 1681664721483, "stop": 1681664722401, "uuid": "a4b1f82d-a6f0-4067-bddf-a6318ba70ed0", "historyId": "6db7b08e3bb2eaea16d6770088295259", "testCaseId": "8a60dce236914ec069ab9ecd190ad614", "fullName": "tests.test_track.TestTrack#test_get_order_status_on_completed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_track"}, {"name": "subSuite", "value": "TestTrack"}, {"name": "host", "value": "workstation"}, {"name": "thread", "value": "181161-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_track"}]}