{"name": "Тест неподтверждения отправки нового заказа с лендинга", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'Б' is invalid: Введите корректную фамилию", "trace": "self = <test_order.TestOrder object at 0x7f11747e6d10>\nwebdriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"ff3bcb40-9a35-42e6-a25a-4f135b1d021c\")>\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"ff3bcb40-9a35-42e6-a25a-4f135b1d021c\")>\n\n    @allure.title('Тест неподтверждения отправки нового заказа с лендинга')\n    @allure.description('Переходим к созданию нового заказа через кнопку в лендинге, \\\n                        заполняем необходимые поля и **не** подтверждаем отправку заказа, \\\n                        проверяем, что вернулись на форму заполнения информации об аренде')\n    def test_order_from_landing_not_confirm(self, webdriver: WebDriver, wait: WebDriverWait):\n        self.__enter_order_from_landing(webdriver, wait)\n>       self.__fill_order_common(webdriver, wait)\n\ntests/test_order.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/test_order.py:101: in __fill_order_common\n    order_customer_page.check_valid_last_name()\npages/order_customer_page.py:63: in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.order_customer_page.OrderCustomerPage object at 0x7f11746ea390>\nlocator = ['xpath', './/input[starts-with(@class, \"Input_Input\") and contains(@placeholder, \"Фамилия\")]']\n\n    def __check_valid_input(self, locator: List[str]):\n        input_element = self.webdriver.find_element(*locator)\n    \n        given_value = input_element.get_attribute('value')\n    \n        input_element.clear()\n        input_element.send_keys(given_value)\n    \n        error_locator = [By.XPATH, f'{locator[1]}/../div']\n    \n        error_element = self.webdriver.find_element(*error_locator)\n    \n        is_valid = len(error_element.text) == 0\n    \n        if not is_valid:\n            allure.attach(\n                body=self.webdriver.get_screenshot_as_png(),\n                name='form-customer-input-validation-error',\n                attachment_type=allure.attachment_type.PNG)\n    \n>       assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\nE       AssertionError: Input 'Б' is invalid: Введите корректную фамилию\n\npages/order_customer_page.py:98: AssertionError"}, "description": "Переходим к созданию нового заказа через кнопку в лендинге,                         заполняем необходимые поля и **не** подтверждаем отправку заказа,                         проверяем, что вернулись на форму заполнения информации об аренде", "steps": [{"name": "Клик на кнопку согласия на использование cookies", "status": "passed", "start": 1681664720686, "stop": 1681664720933}, {"name": "Скролл к кнопке Заказать", "status": "passed", "start": 1681664720933, "stop": 1681664721001}, {"name": "Клик на кнопку Заказать", "status": "passed", "start": 1681664721002, "stop": 1681664721314}, {"name": "Ввод информации о заказчике: имя", "status": "passed", "parameters": [{"name": "value", "value": "'Денис'"}], "start": 1681664721314, "stop": 1681664721365}, {"name": "Проверка валидности ввода: имя", "status": "passed", "start": 1681664721365, "stop": 1681664721520}, {"name": "Ввод информации о заказчике: фамилия", "status": "passed", "parameters": [{"name": "value", "value": "'Блинов'"}], "start": 1681664721520, "stop": 1681664721548}, {"name": "Проверка валидности ввода: фамилия", "status": "failed", "statusDetails": {"message": "AssertionError: Input 'Б' is invalid: Введите корректную фамилию\n", "trace": "  File \"/home/user/qa_python_4/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 63, in check_valid_last_name\n    self.__check_valid_input(self.input_last_name)\n  File \"/home/user/qa_python_4/pages/order_customer_page.py\", line 98, in __check_valid_input\n    assert is_valid, f'Input \\'{given_value}\\' is invalid: {error_element.text}'\n"}, "attachments": [{"name": "form-customer-input-validation-error", "source": "e030df59-08a3-4b2d-ab34-ffe7d2374390-attachment.png", "type": "image/png"}], "start": 1681664721548, "stop": 1681664721704}], "start": 1681664720686, "stop": 1681664721705, "uuid": "a1ad7b69-64df-43f5-a076-05b29bf032ad", "historyId": "cac3f2860f7c0d271550e3eba1ce7db6", "testCaseId": "23c037df7ba3323b68b90f4fd2bfdf75", "fullName": "tests.test_order.TestOrder#test_order_from_landing_not_confirm", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrder"}, {"name": "host", "value": "workstation"}, {"name": "thread", "value": "181173-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}